name: main

on: [push] # on event that tells Github when to run workflow

jobs:
  build:
    runs-on: ubuntu-latest

    #Steps are the actions to be performed after a push 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'

      # Setup Dependencies. PIP & Pytest
      - name: Install Python Dependencies 
        run: | 
          python -m pip install --upgrade pip
          pip install requests pytest
      # Let GitHub know where the scripts are and what to run. Pytest :)
      - name: Test Python Scripts
        working-directory: Python_Scripts/ #Setting up where to run the pytest
        run: pytest
