name: main

on: [push] # on event that tells Github when to run workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'

    #Steps are the actions to be performed after a push 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install Python Dependencies (requests and pytest)
      - name: Install Python Dependencies 
        run: | 
          python -m pip install --upgrade pip
          pip install requests pytest

      # Test Python Scripts using pytest
      - name: Test Python Scripts
        working-directory: Python_Scripts/ #Setting up where to run the pytest
        run: pytest

      # Deploy Terraform Configuration
      - name: Deploy Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.2.0'
      - name: Terraform Init
        working-directory: Terraform/
        run: terraform init
      - name: Terraform Plan
        working-directory: Terraform/
        run: terraform plan
      # - name: Terraform Apply
      #   working-directory: Terraform/
      #   if: success()
      #   run: terraform apply -auto-approve