name: S3 Sync - Web Files

on: 
  push: 
    paths:
      - 'Web_Files/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync Web_Files s3://${{ secrets.CR_S3_BUCKET }} \
            --exclude '*' \
            --include '*.html' \
            --include '*.css' \
            --include '*.js'



  